---
abstract: "Generate pronounceable\npasswords with random case"
author:
  - 'Mario Domgoergen <mdom@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Password-Pronounceable-RandomCase
provides:
  Text::Password::Pronounceable::RandomCase:
    file: lib/Text/Password/Pronounceable/RandomCase.pm
    version: 0.03
requires:
  Readonly: 0
  Text::Password::Pronounceable: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mdom/text-password-pronounceable-randomcase
version: 0.03
