---
name: Text-Password-Pronounceable-RandomCase
version: 0.02
author:
  - 'Mario Domgoergen <mdom@cpan.org>'
abstract: |-
  Generate pronounceable
  passwords with random case
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mdom/text-password-pronounceable-randomcase
build_requires:
  Test::More: 0
requires:
  Readonly: 0
  Text::Password::Pronounceable: 0
  parent: 0
configure_requires:
  Module::Build: 0.35
provides:
  Text::Password::Pronounceable::RandomCase:
    file: lib/Text/Password/Pronounceable/RandomCase.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
